### ISSUE TITLE
Give me an escape hatch to override values from distro

### ISSUE THREAD

**Issue by jonkeane** [nealrichardson/distro#1]
When testing if a particular mapping would work updating [the arrow-r-nightly distro-map.csv](https://github.com/ursa-labs/arrow-r-nightly/blob/master/linux/distro-map.csv) I found myself wanting to be able to override an ubuntu version number temporarily. I ended up accomplishing this by editing `/usr/lib/os-release` which `lsb-release` uses to get its values, but that's specific to each distro + not a great practice on a running machine.

I would like the ability to set env vars like `DISTRO_ID` that will override whatever is in the `id` element of the returned value. That way one could set `DISTRO_VERSION="20.04" R -e "install_arrow()"` and get the 20.04 binary to test if it is compatible with the version one is on.

**Comment by nealrichardson** [comment]
I'm not sure if this is something that should be solved in `distro`. For your particular use case, you could set `LIBARROW_BINARY=ubuntu-20.04` (or whatever) to tell `arrow` to download the binary of your choice.

**Comment by jonkeane** [comment]
Aaah true, I have only ever tried `true/false` for `LIBARROW_BINARY`, but sure enough that does work! Thanks
